### ISSUE TITLE
USER STORY: Provide anonymous poll response

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/my-first-agile-project#5]
In order to **hide my identity** as a **voter in the poll**, I can **check a hide identity box**

## Acceptance Criteria:
* Acceptance Criteria 1: Checkbox to be included below poll to hide identity of user
* Acceptance Criteria 2: Checkbox is only clickable once poll has been voted on
* Acceptance Criteria 3: Confirm to the user their identity is hidden

## Tasks
- [ ] Create checkbox titled "hide identity"
- [ ] Give functionality for poll vote to be required in order to check box
- [ ] Provide confirmation of hidden identity
- [ ] Test functionality
