### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by mtmanning93** [mtmanning93/my-first-agile-project#6]
In order to **collect users feedback**, as an **administrator**, I can **publish a poll**.

## Acceptance Criteria:
* Acceptance Criteria 1: Admin should be able to create a poll by adding poll items to vote on
* Acceptance Criteria 2: Admin should be able to decide when to publish the poll
* Acceptance Criteria 3: Admin must be able to see results of the poll, throughout voting

## Tasks
- [ ] Update Admin module view to create poll (HTML/ CSS already in place, just add poll names)
- [ ] Add a publish button to the create poll module
- [ ] Decide on placement of published poll on the main site
- [ ] Provide statistical feedback from the poll in the form of %, only available in the Admin view
- [ ] Test functionality
